### ISSUE TITLE
Error running `aragon run`

### ISSUE THREAD

**Issue by adklempner** [aragon/aragon-example-application#8]
```
✖ aragon <command> requires a network 'development' in your truffle.js. For an example, see http://truffleframework.com/docs/advanced/configuration
```

**Comment by luisivan** [comment]
Do you have a network called "development" in your truffle.js file? If not, add/rename it

**Comment by sohkai** [comment]
@adklempner closing this for #3 as this repo's `truffle.json` should already include the development network.
